# Generated by Django 3.2.8 on 2021-10-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residencial', models.CharField(max_length=14, null=True)),
                ('celular', models.CharField(max_length=12)),
                ('outro', models.CharField(max_length=14, null=True)),
            ],
            options={
                'db_table': 'en_telefones',
            },
        ),
    ]
