# Generated by Django 3.2.8 on 2021-10-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='celular',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='outro',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='residencial',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
