# Generated by Django 3.2.8 on 2021-10-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefones', '0002_auto_20211023_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='celular',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='outro',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='residencial',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
