# Generated by Django 3.2.8 on 2021-10-25 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Previsao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn_est', models.CharField(max_length=150)),
                ('temp', models.FloatField()),
            ],
            options={
                'db_table': 'en_previsao',
            },
        ),
    ]
