# Generated by Django 3.2.8 on 2021-10-23 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='en_usuarios',
        ),
    ]
