# Generated by Django 3.2.8 on 2021-11-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='empresas',
            field=models.ManyToManyField(blank=True, null=True, related_name='usuario', to='empresas.Empresa'),
        ),
    ]
