# Generated by Django 3.2.8 on 2021-10-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
