# Generated by Django 3.2.8 on 2021-10-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_remove_empresa_usuarios'),
        ('usuarios', '0005_usuario_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empresas',
            field=models.ManyToManyField(to='empresas.Empresa'),
        ),
    ]
