# Generated by Django 3.2.8 on 2021-11-25 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacaoModelo',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('latlong', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'en_estacoes_modelo',
            },
        ),
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('empresa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='estacoes', to='empresas.empresa')),
                ('estacao_modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estacoes.estacaomodelo')),
            ],
            options={
                'db_table': 'en_estacoes',
            },
        ),
    ]
