# Generated by Django 3.2.8 on 2021-11-25 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacao',
            name='estacao_modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estacoes.estacaomodelo'),
        ),
    ]
