# Generated by Django 3.2.8 on 2021-10-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacoes', '0002_alter_estacao_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='latitude',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estacao',
            name='longitude',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
