# Generated by Django 3.2.8 on 2021-10-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacoes', '0003_auto_20211024_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacao',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
