# Generated by Django 3.2.8 on 2022-02-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacoes', '0003_auto_20220216_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacao',
            name='latitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='longitude',
            field=models.IntegerField(),
        ),
    ]
