# Generated by Django 3.2.8 on 2021-10-24 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_usuarios'),
        ('estacoes', '0004_alter_estacao_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacao',
            name='empresa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='estacoes', to='empresas.empresa'),
        ),
    ]
