# Generated by Django 3.2.8 on 2021-10-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
