# Generated by Django 3.2.8 on 2021-10-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
