# Generated by Django 3.2.8 on 2021-10-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_cpf'),
        ('empresas', '0002_auto_20211023_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(to='usuarios.Usuario'),
        ),
    ]
