# Generated by Django 3.2.8 on 2021-10-24 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='usuarios',
        ),
    ]
