# Generated by Django 3.2.8 on 2021-11-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_auto_20211028_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
