# Generated by Django 3.2.8 on 2021-10-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area_cultivo', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'en_cultivos',
            },
        ),
    ]
