# Generated by Django 3.2.8 on 2021-10-23 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
    ]
