# Generated by Django 3.2.8 on 2021-10-24 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20211023_0304'),
        ('cultivos', '0002_cultivo_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='empresas.empresa'),
        ),
    ]
